Add MinionPrePlaceEvent + MinionLinkChestEvent
Artillex-Studios/AxMinions pull request #13
Opened 2024-04-30 10:12 UTC by rudde0

It should help to plugin devs in many aspects.

In my case,

- MinionPrePlaceEvent: I'm gonna pass the player limit by the method, and I'll write my own limit method for per island.
- MinionChestLinkEvent: I'll cancel the event if chest is not special chest.

2024-04-30 16:10 UTC, AverageGithub requested changes
I really appreciate your efforts! I requested some changes, but otherwise great job and thank you for your contribution!

2024-04-30 21:13 UTC, rudde0 commented
> I really appreciate your efforts! I requested some changes, but otherwise great job and thank you for your contribution!

I can't see your reviews, which changes should I do, could you rewrite please.

In other hand, AxMinions saved me crazy amount of times against handling the minions. So, thanks are belongs to you.

2024-05-01 15:30 UTC, AverageGithub requested changes
I hope it works this time, Github didn't want me to review lol.

2024-05-01 15:30 UTC, AverageGithub commented on api/src/main/kotlin/com/artillexstudios/axminions/api/events/MinionPrePlaceEvent.kt
> +class MinionPrePlaceEvent(private val player: Player) : Cancellable, Event() {
Could this be renamed to PreMinionPlaceEvent?

2024-05-01 15:30 UTC, AverageGithub commented on common/src/main/kotlin/com/artillexstudios/axminions/minions/Minion.kt
> +        if(preBreakEvent.isCancelled) return
Could you add a space between the if and the "("? I'd appreciate if you made this change in the other places aswell.

2024-05-01 15:30 UTC, AverageGithub commented on api/src/main/kotlin/com/artillexstudios/axminions/api/events/MinionPreBreakEvent.kt
> +class MinionPreBreakEvent(private val player: Player, minion: Minion) : MinionEvent(minion), Cancellable {
Could this be renamed to PreMinionPickupEvent?

2024-05-02 14:47 UTC, AverageGithub approved these changes
Thank you for your contribution! You can expect this version to be released soon, I'd like to add 1.20.5/6 support before releasing though.

2024-05-02 14:47 UTC, merged